CREATE VIEW [dbo].[V_CHARACTERS]
	AS 
WITH CTE_FRIENDS AS (
	SELECT 
		CHARACTERID,
		FORMATMESSAGE('["%s"]', STRING_AGG(F.NAME, '", "')) FRIENDS
	FROM RELATIONSHIPS RS
	JOIN CHARACTERS F ON F.ID = RS.FRIENDID
	GROUP BY CHARACTERID
)
,CTE_EPISODES AS (
	SELECT 
		CHARACTERID, 
		FORMATMESSAGE('["%s"]', STRING_AGG(E.NAME, '", "')) EPISODES
	FROM CASTS C
	JOIN EPISODES E ON E.ID = C.EPISODEID
	GROUP BY CHARACTERID
)
SELECT 
	CH.ID, 
	CH.NAME, 
	E.EPISODES,
	F.FRIENDS
FROM CHARACTERS CH
JOIN CTE_FRIENDS F ON F.CHARACTERID = CH.ID
JOIN CTE_EPISODES E ON E.CHARACTERID = CH.ID