CREATE TABLE [dbo].[CASTS]
(
	[EPISODEID] INT NOT NULL,
	[CHARACTERID] INT NOT NULL,
	CONSTRAINT [PK_CAST] PRIMARY KEY ([EPISODEID], [CHARACTERID]), 
    CONSTRAINT [FK_CASTS_EPISODES] FOREIGN KEY ([EPISODEID]) REFERENCES [EPISODES]([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_CASTS_CHARACTERS] FOREIGN KEY ([CHARACTERID]) REFERENCES [CHARACTERS]([ID]) ON DELETE CASCADE,
)
