CREATE TABLE [dbo].[CHARACTERS] (
    [ID]   INT            NOT NULL IDENTITY(1,1),
    [NAME] NVARCHAR (255) NOT NULL,
	CONSTRAINT PK_CHARACTER PRIMARY KEY(ID)
);


GO

CREATE TRIGGER [dbo].[TR_CHARACTERS_DELETE]
    ON [dbo].[CHARACTERS]
    INSTEAD OF DELETE
    AS
    BEGIN
		DELETE RELATIONSHIPS WHERE CHARACTERID IN (SELECT ID FROM deleted);
		DELETE RELATIONSHIPS WHERE FRIENDID IN (SELECT ID FROM deleted);
		DELETE CHARACTERS WHERE ID IN (SELECT ID FROM deleted);
    END