CREATE TABLE [dbo].[RELATIONSHIPS]
(
	[CHARACTERID] INT NOT NULL,
	[FRIENDID] INT NOT NULL,
	PRIMARY KEY ([CHARACTERID], [FRIENDID]),
    CONSTRAINT [FK_RELATIONSHIPS_CHARACTERS_CHARACTERID] FOREIGN KEY ([CHARACTERID]) REFERENCES [CHARACTERS]([ID]),
	CONSTRAINT [FK_RELATIONSHIPS_CHARACTERS_FRIENDID] FOREIGN KEY ([FRIENDID]) REFERENCES [CHARACTERS]([ID]), 
    CONSTRAINT [CK_RELATIONSHIPS_NOTSAME] CHECK ([CHARACTERID] != [FRIENDID]),
)
